tenancy:
  master:
    datasource:
      url: jdbc:postgresql://pg.rndpro.in:5432/tenant_db
      username: tenant_user
      password: Tenant1234
      driverClassName: org.postgresql.Driver
      connectionTimeout: 20000
      maxPoolSize: 250
      idleTimeout: 300000
      minIdle: 5
      poolName: masterdb-connection-pool